services:
  deva-course-web:
    build: .
    container_name: deva-course-web
    environment:
      VIRTUAL_HOST: deva-course.iohtechco.com
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: deva-course.iohtechco.com
      LETSENCRYPT_EMAIL: deswandhi@ioh.co.id
    ports:
      - "127.0.0.1:8082:80"
    restart: unless-stopped
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
